### ISSUE TITLE
Feature: animations

### ISSUE THREAD

**Issue by manvankaliber** [UltraCakeBakery/cssified-html#20]
I've been thinking about this for a bit. What if you could define animations through html elements?

###### EXAMPLE:

HTML:
```html
<html>
	<animation name="keyframes-example">
		<keyframe:0% background="red" />
		<keyframe:25% background="green" />
		<keyframe:50% background="blue" />
		<keyframe:100% background="white" />
	</animation>
	<div animation="keyframes-example"></div>
</html>
```

GENERATED CSS:

```css
animation { display: none } // Hides the animation element

@keyframes keyframes-example {
  0%   {background-color: red;}
  25%  {background-color: green;}
  50%  {background-color: blue;}
  100% {background-color: white;}
}

[animation="keyframes-example"] { animation: keyframes-example; }
```
